### ISSUE TITLE
Parent view is losing background color if swipe to go back is enabled inside navigation controller

### ISSUE THREAD

**Issue by giacomoferrari** [Ramotion/paper-switch#14]
if i had a switch turned on inside a view and i do swipe right to navigate to previous controller, the parent view of the switch has lost his color
![84f0b970-f086-4d34-9546-98a5b1d1d507](https://cloud.githubusercontent.com/assets/7880883/15198553/571cf4e2-17d8-11e6-8160-938811572f0b.jpg)

**Comment by ober01** [comment]
override method in your cell 

```
prepareForReuse() {
  super. prepareForReuse()
  // SET CURRENT COLOR 
}
```

**Comment by giacomoferrari** [comment]
The parent views aren't cells, they are UIView inside a stackview.

I must use a table row for achieving what I need and avoid this problem or I can still go my way and resolve this issue in some way?

**Comment by giacomoferrari** [comment]
Can't resolve this issue, any hint?
I would love to integrate your switch in production

**Comment by giacomoferrari** [comment]
Even with the last commit, the problem is still there.

Parent view is losing color if I'm swiping back from a navigation controller

**Comment by giacomoferrari** [comment]
Now it's working! Thank u very much!
