### ISSUE TITLE
Issue when switch is set to true from init.

### ISSUE THREAD

**Issue by henryhardy** [Ramotion/paper-switch#15]
Hi!

Love your work. I have an issue where if i set the .setOn property to true, then the switch doesn't work. When I toggle it, it won't change the color of the view.

Do you have any way around this?

**Comment by henryhardy** [comment]
Hi!

So if I use the code below

```
   let magicSwitch = RAMPaperSwitch(view: self.contentView, color: Styles().heyGreen())
    magicSwitch.setOn(true, animated: false)
    self.contentView.addSubview(shotBlockSwitch)
```

then tap on the switch, nothing changes other than that the switch changes again. See dropbox link to see image.

https://www.dropbox.com/s/8qblzy5mbecvcja/Screenshot%202016-06-20%2016.27.22.png?dl=0

It takes on the correct color as defined when you initiate it, but won't change or pull the color back in to reveal the view color underneath after that.

**Comment by ober01** [comment]
Sorrry I can't reproduce. Reproduce bug in this project https://github.com/ober01/PaperSwitchExample
