### ISSUE TITLE
finding the colours that paper-switch

### ISSUE THREAD

**Issue by Praize** [Ramotion/paper-switch#25]
please help me fin a way to change the colours and put my own.

**Comment by igork-ramotion** [comment]
@Praize Hi!) In Demo you can find this in PaperSwitch "Attributes Inspector" as `On Tint`. Please take a look at the screenshot 

<img width="1508" alt="PaperSwitch_TintColor" src="https://user-images.githubusercontent.com/53435668/68676924-1a0eb600-056c-11ea-924f-f0f599ae6c65.png">

It also can be changed programmatically
