### ISSUE TITLE
Objective-c Compatibility

### ISSUE THREAD

**Issue by remirobert** [Ramotion/paper-switch#4]
Is it compatible Objective-c ? The override change stat doesn't call with Objective-c code.
Thanks in advance.

**Comment by JigarM** [comment]
you can import the swift file in the Objective C project using bridging header.
Check this : 
http://stackoverflow.com/questions/24002369/how-to-call-objective-c-code-from-swift

**Comment by JigarM** [comment]
@remirobert : just use paper switch in Obj C Code :
 https://github.com/JigarM/paper-switch-ObjectiveC

**Comment by remirobert** [comment]
It doesn't work for me programtly, from a UItableViewCell or a simple UIView.
self.switchResponse = [[RAMPaperSwitch alloc] init];
    self.switchResponse.frame = CGRectMake(self.mainView.frame.size.width - self.switchResponse.frame.size.width - 10, 0,
                                           self.switchResponse.frame.size.width, self.switchResponse.frame.size.height);

    [self.mainView addSubview:self.switchResponse];
    [self.switchResponse setOnTintColor:[UIColor blueColor]];
